org.gradle.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=2
kotlin.daemon.jvmargs=-Xmx768m
org.gradle.caching=true
org.gradle.configuration-cache=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.overridePathCheck=true
kotlin.code.style=official
zapretVersionName=5.9.1
zapretVersionCode=116
zapretDebugVersionNameSuffix=
zapretPanelUpdateBaseUrl=https://tepacom.o190.com:8443
