org.gradle.jvmargs=-Xmx512m -Dfile.encoding=UTF-8 -XX:+UseSerialGC -Xss256k
org.gradle.parallel=false
org.gradle.workers.max=2
kotlin.daemon.jvmargs=-Xmx256m -Xss256k
org.gradle.caching=true
org.gradle.configuration-cache=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.overridePathCheck=true
kotlin.code.style=official
zapretVersionName=5.9.8
zapretVersionCode=123
zapretDebugVersionNameSuffix=
zapretPanelUpdateBaseUrl=https://pecaocek.ignorelist.com:8443
