package com.quantumvpn.resources

import com.quantumvpn.routing.RemoteRoutingPolicyVerifier
import java.util.Base64
import kotlinx.serialization.json.*
import net.i2p.crypto.eddsa.EdDSAEngine
import net.i2p.crypto.eddsa.EdDSAPrivateKey
import net.i2p.crypto.eddsa.spec.EdDSANamedCurveTable
import net.i2p.crypto.eddsa.spec.EdDSAPrivateKeySpec
import org.junit.Assert.*
import org.junit.Test

class AppResourceVerifierTest {
    private val key = EdDSAPrivateKey(EdDSAPrivateKeySpec(ByteArray(32) { (it + 1).toByte() }, EdDSANamedCurveTable.getByName("Ed25519")))
    private val publicKey = Base64.getUrlEncoder().withoutPadding().encodeToString(key.abyte)
    private fun payload() = Json.parseToJsonElement("""{"kind":"quantumvpn-resources-v1","sequence":3,"revision":1,"min_version_code":501101099,"texts":{"welcome":"Привет!"},"theme":{"accent":"#58F4CE","compact_home":true},"assets":{}}""").jsonObject
    private fun sign(p: JsonObject): String {
        val bytes = RemoteRoutingPolicyVerifier.canonicalJson(p).toByteArray()
        val signature = EdDSAEngine().apply { initSign(key); update(bytes) }.sign()
        return buildJsonObject {
            put("schema", 1); put("signature_algorithm", "ed25519"); put("payload", p)
            put("public_key", publicKey); put("sha256", AppResourceVerifier.sha256(bytes))
            put("signature", Base64.getUrlEncoder().withoutPadding().encodeToString(signature))
        }.toString()
    }
    private fun verify(raw: String = sign(payload()), minimum: Long = 0, version: Long = 501101099) = AppResourceVerifier.verify(raw, version, minimum, publicKey)
    private fun rejected(block: () -> Unit) {
        try { block(); fail("Untrusted or invalid package accepted") } catch (_: IllegalArgumentException) { }
        catch (_: IllegalStateException) { }
    }
    private fun changed(field: String, value: JsonElement): String = sign(JsonObject(payload() + (field to value)))

    @Test fun acceptsSignatureAndRollbackRevisionWithNewSequence() {
        val value = verify(minimum = 2)
        assertEquals(1L, value.revision)
        assertEquals(3L, value.sequence)
        assertEquals("Привет!", value.text("welcome", "fallback"))
        assertEquals("fallback", value.text("tagline", "fallback"))
        assertTrue(value.compactHome)
    }
    @Test fun acceptsRealPythonServerSignatureWithUnicode() {
        // Generated by tools.quantumvpn_resources with the public test-only seed above.
        val vector = """{"schema":1,"signature_algorithm":"ed25519","payload":{"kind":"quantumvpn-resources-v1","sequence":3,"revision":1,"min_version_code":501101099,"texts":{"welcome":"\u041f\u0440\u0438\u0432\u0435\u0442!"},"theme":{"accent":"#58F4CE","compact_home":true},"assets":{}},"sha256":"c8ac9a2b11719e4a890f673b16713893f2db0c53485f4d9900f3370a58795380","public_key":"ebVWLo_mVPlAeLES6KmLp5AfhTrmlb7X4OORC60ElmQ","signature":"ury4w3czJ4fT-cFMg19T21cDrY1xBiY6DLYX93oMEyD3aPnY2lCNazHzVSu7C3kpFyZ-bk1GPdzWdqE0MAtcAA"}"""
        assertEquals("Привет!", verify(vector).texts["welcome"])
    }
    @Test fun rejectsTamperedContent() { rejected { verify(sign(payload()).replace("Привет!", "Подмена")) } }
    @Test fun responseKeyIsNotTrusted() { rejected { AppResourceVerifier.verify(sign(payload()), 501101099) } }
    @Test fun rejectsOldSequence() { rejected { verify(minimum = 4) } }
    @Test fun rejectsIncompatibleApp() { rejected { verify(version = 501101098) } }
    @Test fun rejectsWrongPurposeEvenSigned() { rejected { verify(changed("kind", JsonPrimitive("routing"))) } }
    @Test fun rejectsExecutableFieldsEvenSigned() { rejected { verify(changed("code", JsonPrimitive("run()"))) } }
    @Test fun rejectsBadColor() { rejected { verify(changed("theme", buildJsonObject { put("accent", "red") })) } }
    @Test fun rejectsUrlAndUnknownTheme() { rejected { verify(changed("theme", buildJsonObject { put("url", "https://evil.test") })) } }
    @Test fun rejectsStringBooleans() { rejected { verify(changed("theme", buildJsonObject { put("compact_home", "true") })) } }
    @Test fun rejectsLongTextAndUnknownText() {
        rejected { verify(changed("texts", buildJsonObject { put("welcome", "x".repeat(121)) })) }
        rejected { verify(changed("texts", buildJsonObject { put("javascript", "eval") })) }
    }
    @Test fun rejectsAssetUrlAndOversize() {
        val asset = buildJsonObject { put("sha256", "a".repeat(64)); put("size", AppResourceVerifier.MAX_ASSET + 1); put("mime", "image/png"); put("width", 2); put("height", 2) }
        rejected { verify(changed("assets", buildJsonObject { put("background", asset) })) }
        rejected { verify(changed("assets", buildJsonObject { put("background", JsonObject(asset + ("url" to JsonPrimitive("https://evil.test")))) })) }
    }
    @Test fun rejectsOversizedManifest() { rejected { verify(" ".repeat(AppResourceVerifier.MAX_MANIFEST + 1)) } }
    @Test fun equalSequenceAllowedOnlyForIdenticalVerifiedPayload() { assertEquals(verify().digest, verify(minimum = 3).digest) }
}
